(function(){
var URL='https://app.calldirector.ai/api/public/landing-pages/7651/sheet-data',all=[],cur='All',initialLevel='';
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function yes(v){return /^(yes|y|true|1)$/i.test(String(v||'').trim())}
function meta(l,v){return v?'<div><dt>'+esc(l)+'</dt><dd>'+esc(v)+'</dd></div>':''}
function card(r){var price=r['Price']||'';var hasStart=String(r['Start date']||'').trim();var hasDays=String(r['Days and times']||'').trim();var notes=String(r['Notes']||'').trim();var reg=String(r['Register link']||'').trim();var btn=reg.indexOf('https://')===0?'<a class="btn" href="'+esc(reg)+'">Register &amp; pay</a>':'<a class="btn" href="../classes/#request">Request this class</a>';return '<article class="card"><span class="tg">'+esc(r['Level']||'Class')+'</span><h3>'+esc(r['Class'])+'</h3>'+(r["What you'll make"]?'<p>'+esc(r["What you'll make"])+'</p>':'')+'<div class="price-line">'+esc(price)+'</div>'+((hasStart||hasDays)?'<dl class="detail-grid">'+meta('Starts',r['Start date'])+meta('Length',r['Length'])+meta('Days &amp; times',r['Days and times'])+meta('Spots left',r['Spots left'])+'</dl>':'<p class="fine">Dates are announced soon. Ask us about the next session.</p>')+(notes?'<p class="fine">'+esc(notes)+'</p>':'')+'<div class="actions">'+btn+'<a class="smalllink" href="tel:+12406980342">Questions? Call 240-698-0342</a></div></article>'}
function draw(){var rows=all.filter(function(r){return cur==='All'||r['Level']===cur});document.getElementById('list').innerHTML=rows.length?rows.map(card).join(''):'<div class="note" style="grid-column:1/-1">New classes are posted here as soon as they are scheduled. Call <a href="tel:+12406980342">240-698-0342</a> or send a request and we will tell you what is coming up.</div>'}
function chips(){var lv=['All'];all.forEach(function(r){if(r['Level']&&lv.indexOf(r['Level'])<0)lv.push(r['Level'])});var f=document.getElementById('filters');if(lv.length<3){f.innerHTML='';return}if(!cur||lv.indexOf(cur)<0)cur='All';f.innerHTML=lv.map(function(l){return '<button type="button" class="btn sm '+(l===cur?'':'out')+'" aria-pressed="'+(l===cur)+'" data-l="'+esc(l)+'">'+esc(l)+'</button>'}).join('');Array.prototype.forEach.call(f.querySelectorAll('button'),function(b){b.onclick=function(){cur=b.getAttribute('data-l');chips();draw()}})}
function applyInitial(){var qp=new URLSearchParams(location.search).get('class');if(qp){initialLevel=qp;}}
applyInitial();
fetch(URL).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(j){all=(j.data||[]).filter(function(r){return yes(r['Show on site'])&&r['Class']});var levels=all.map(function(r){return r['Level']}).filter(Boolean);if(initialLevel&&levels.indexOf(initialLevel)>=0)cur=initialLevel;chips();draw();if(initialLevel&&levels.indexOf(initialLevel)>=0){document.getElementById('list').scrollIntoView({behavior:'smooth',block:'start'})}}).catch(function(){document.getElementById('list').innerHTML='<div class="note" style="grid-column:1/-1">We could not load the schedule just now. Please call <a href="tel:+12406980342">240-698-0342</a> or send a request and we will help.</div>'});
})();

(function(){var b=document.getElementById('bg'),n=document.getElementById('nv');b.addEventListener('click',function(){var o=n.classList.toggle('open');b.setAttribute('aria-expanded',o)});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&n.classList.contains('open')){n.classList.remove('open');b.setAttribute('aria-expanded','false');b.focus()}})})();