(function(){
var URL='https://app.calldirector.ai/api/public/landing-pages/7651/sheet-data',all=[],cur='All';
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function yes(v){return /^(yes|y|true|1)$/i.test(String(v||'').trim())}
function meta(l,v){return v?'<div><dt style="font-size:.74rem;text-transform:uppercase;letter-spacing:.05em;color:#555">'+l+'</dt><dd style="margin:0 0 4px;font-weight:500">'+esc(v)+'</dd></div>':''}
function card(r){return '<article class="card"><span class="tg">'+esc(r['Level']||'Class')+'</span>'+(yes(r['Sample row'])?'<span class="tg" style="background:#FFF1B8;color:#6b5200">Sample listing</span>':'')+'<h3>'+esc(r['Class'])+'</h3>'+(r["What you'll make"]?'<p>'+esc(r["What you'll make"])+'</p>':'')+'<dl style="display:grid;grid-template-columns:1fr 1fr;gap:6px 14px;margin:12px 0;font-size:.92rem">'+meta('Starts',r['Start date'])+meta('Length',r['Length'])+meta('Days &amp; times',r['Days and times'])+meta('Price',r['Price'])+meta('Spots left',r['Spots left'])+'</dl><a class="btn sm" href="../classes/#request">Request this class</a></article>'}
function draw(){var rows=all.filter(function(r){return cur==='All'||r['Level']===cur});document.getElementById('list').innerHTML=rows.length?rows.map(card).join(''):'<div class="note" style="grid-column:1/-1">New classes are posted here as soon as they are scheduled. Call <a href="tel:+12406980342">240-698-0342</a> or send a request and we will tell you what is coming up.</div>'}
function chips(){var lv=['All'];all.forEach(function(r){if(r['Level']&&lv.indexOf(r['Level'])<0)lv.push(r['Level'])});var f=document.getElementById('filters');if(lv.length<3){f.innerHTML='';return}f.innerHTML=lv.map(function(l){return '<button type="button" class="btn sm '+(l===cur?'':'out')+'" aria-pressed="'+(l===cur)+'" data-l="'+esc(l)+'">'+esc(l)+'</button>'}).join('');Array.prototype.forEach.call(f.querySelectorAll('button'),function(b){b.onclick=function(){cur=b.getAttribute('data-l');chips();draw()}})}
fetch(URL).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(j){all=(j.data||[]).filter(function(r){return yes(r['Show on site'])&&r['Class']});chips();draw()}).catch(function(){document.getElementById('list').innerHTML='<div class="note" style="grid-column:1/-1">We could not load the schedule just now. Please call <a href="tel:+12406980342">240-698-0342</a> or send a request and we will help.</div>'});
})();

(function(){var b=document.getElementById('bg'),n=document.getElementById('nv');b.addEventListener('click',function(){var o=n.classList.toggle('open');b.setAttribute('aria-expanded',o)});document.addEventListener('keydown',function(e){if(e.key==='Escape'&&n.classList.contains('open')){n.classList.remove('open');b.setAttribute('aria-expanded','false');b.focus()}})})();